apiVersion: apps/v1
kind: Deployment
metadata:
  name: dds-subscriber-deployment
  labels:
    app: dds-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dds-subscriber
  template:
    metadata:
      labels:
        app: dds-subscriber
    spec:
      containers:
      - name: dds-subscriber
        image: dds-app:latest
        imagePullPolicy: Never # Use 'Never' or 'IfNotPresent' since the image is built locally
        
        # 🐛 THE FIX: Explicitly set the command to run the subscriber binary
        # This overrides the Dockerfile's ENTRYPOINT/CMD, preventing the shell crash.
        command: ["/usr/local/bin/subscriber"]
        
        # If your subscriber needed arguments, you would use:
        # args: ["--topic", "MyTopic"]